import { Listing } from './types';

export const mockListings: Listing[] = [
  {
    id: '1',
    title: 'Cedar Ridge — Woodland Retreat',
    description:
      'Nestled among silver birches, this hand-crafted THOW is the ultimate escape. Every inch is intentional: white-oak countertops, a lofted sleeping area with skylights, and a 400W solar array powering everything silently. Step outside to a private deck overlooking a seasonal creek.',
    price: 35000,
    priceType: 'both',
    sqft: 280,
    bedrooms: 1,
    bathrooms: 1,
    location: 'Asheville, NC',
    state: 'North Carolina',
    coordinates: { lat: 35.5951, lng: -82.5515 },
    coverImage: '/listing-1.png',
    images: ['/listing-1.png', '/hero-bg.png'],
    homeType: 'on-wheels',
    offGridScore: 88,
    specs: {
      solarWattage: 400,
      waterSystem: 'Rainwater + filtration',
      insulationRValue: 24,
      toiletType: "Nature's Head composting",
      loftCount: 1,
      heatingType: 'Propane radiant + mini-split',
      rainwaterCollection: true,
      greyWaterSystem: true,
    },
    amenities: ['Solar Panels', 'Solar Power', 'Composting Toilet', 'Rainwater', 'Loft', 'Deck', 'High-speed Internet'],
    isFeatured: true,
    status: 'active',
    monthlyRent: 1100,
    downPaymentPct: 20,
    financeTermMonths: 60,
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    title: 'Summit View — Mountain Modern',
    description:
      'A design-forward foundation home perched at 6,200ft with panoramic mountain views. Floor-to-ceiling glass on the south wall floods the space with light. The open-plan kitchen/living area flows to a wraparound deck where elk are regular visitors. Fully grid-tied with an 800W solar backup.',
    price: 58000,
    priceType: 'both',
    sqft: 420,
    bedrooms: 2,
    bathrooms: 1,
    location: 'Breckenridge, CO',
    state: 'Colorado',
    coordinates: { lat: 39.4817, lng: -106.0384 },
    coverImage: '/listing-2.png',
    images: ['/listing-2.png', '/listing-1.png'],
    homeType: 'foundation',
    offGridScore: 72,
    specs: {
      solarWattage: 800,
      waterSystem: 'Municipal + well backup',
      insulationRValue: 38,
      toiletType: 'Standard low-flow',
      loftCount: 1,
      heatingType: 'Radiant floor + heat pump',
      rainwaterCollection: false,
      greyWaterSystem: true,
    },
    amenities: ['Solar Panels', 'Solar Power', 'Radiant Heat', 'Mountain Views', 'EV Charging', 'Smart Home', 'Fiber Internet'],
    isFeatured: true,
    status: 'active',
    monthlyRent: 1800,
    downPaymentPct: 20,
    financeTermMonths: 60,
    createdAt: '2024-02-01T10:00:00Z',
  },
  {
    id: '3',
    title: 'The Dune Cottage — Coastal Charmer',
    description:
      'A quarter-mile from the surf, this sun-bleached beauty is your permanent vacation. White-washed shiplap, ocean-blue accents, and a breezy front porch with two rocking chairs. Wake up to sea air and fall asleep to waves.',
    price: 22000,
    priceType: 'both',
    sqft: 320,
    bedrooms: 1,
    bathrooms: 1,
    location: 'Outer Banks, NC',
    state: 'North Carolina',
    coordinates: { lat: 35.9049, lng: -75.6718 },
    coverImage: '/listing-3.png',
    images: ['/listing-3.png', '/listing-2.png'],
    homeType: 'foundation',
    offGridScore: 45,
    specs: {
      solarWattage: undefined,
      waterSystem: 'Municipal',
      insulationRValue: 19,
      toiletType: 'Standard',
      loftCount: 0,
      heatingType: 'Mini-split',
      rainwaterCollection: false,
      greyWaterSystem: false,
    },
    amenities: ['Ocean Views', 'Beach Access', 'Outdoor Shower', 'Kayak Storage', 'BBQ Grill', 'WiFi'],
    isFeatured: true,
    status: 'active',
    monthlyRent: 900,
    downPaymentPct: 20,
    financeTermMonths: 48,
    createdAt: '2024-02-14T10:00:00Z',
  },
  {
    id: '4',
    title: 'Sol Terra — Desert Off-Grid',
    description:
      "The most self-sufficient home in our catalog. Built for the Southwest's intense sun and silence, Sol Terra generates more energy than it uses. A battery wall, a 5,000-gallon rainwater cistern, and a passive cooling thermal mass design make this a true homestead.",
    price: 48000,
    priceType: 'both',
    sqft: 360,
    bedrooms: 1,
    bathrooms: 1,
    location: 'Sedona, AZ',
    state: 'Arizona',
    coordinates: { lat: 34.8697, lng: -111.7609 },
    coverImage: '/listing-4.png',
    images: ['/listing-4.png', '/listing-3.png'],
    homeType: 'foundation',
    offGridScore: 97,
    specs: {
      solarWattage: 1200,
      waterSystem: '5,000-gal cistern + well',
      insulationRValue: 42,
      toiletType: 'Sun-Mar composting',
      loftCount: 0,
      heatingType: 'Passive solar + wood stove',
      rainwaterCollection: true,
      greyWaterSystem: true,
    },
    amenities: ['Solar Panels', 'Solar Power', 'Full Off-Grid', 'Battery Wall', 'Rainwater Cistern', 'Red Rock Views', 'Stargazing Deck', 'Root Cellar'],
    isFeatured: false,
    status: 'active',
    monthlyRent: 1400,
    downPaymentPct: 20,
    financeTermMonths: 60,
    createdAt: '2024-03-01T10:00:00Z',
  },
  {
    id: '5',
    title: 'Lakeview A-Frame — Autumn Escape',
    description:
      'The quintessential cozy cabin, reimagined. This Scandinavian-influenced A-Frame sits on a private lakefront lot with its own dock. Rent by the week or buy to own. The soaring ceiling, wood-burning stove, and massive lake-facing window create a cozy retreat.',
    price: 28000,
    priceType: 'both',
    sqft: 240,
    bedrooms: 1,
    bathrooms: 1,
    location: 'Lake Placid, NY',
    state: 'New York',
    coordinates: { lat: 44.2795, lng: -73.9799 },
    coverImage: '/listing-5.png',
    images: ['/listing-5.png', '/listing-4.png'],
    homeType: 'foundation',
    offGridScore: 58,
    specs: {
      solarWattage: undefined,
      waterSystem: 'Lake pump + filtration',
      insulationRValue: 32,
      toiletType: 'Composting',
      loftCount: 1,
      heatingType: 'Wood stove + electric baseboard',
      rainwaterCollection: false,
      greyWaterSystem: true,
    },
    amenities: ['Lakefront', 'Private Dock', 'Kayaks Included', 'Wood Stove', 'Fishing', 'Stargazing'],
    isFeatured: false,
    status: 'active',
    monthlyRent: 850,
    downPaymentPct: 20,
    financeTermMonths: 48,
    createdAt: '2024-03-10T10:00:00Z',
  },
  {
    id: '6',
    title: 'Meadowlark THOW — Farmhouse Wanderer',
    description:
      'Take your homestead with you. This lovingly crafted tiny home on wheels features board-and-batten white siding, a forest-green metal roof, and a Dutch door that opens to wildflowers wherever you park. Fully road-legal on a custom steel trailer.',
    price: 18000,
    priceType: 'both',
    sqft: 220,
    bedrooms: 1,
    bathrooms: 1,
    location: 'Portland, OR',
    state: 'Oregon',
    coordinates: { lat: 45.5051, lng: -122.675 },
    coverImage: '/listing-1.png',
    images: ['/listing-1.png', '/listing-5.png'],
    homeType: 'on-wheels',
    offGridScore: 78,
    specs: {
      solarWattage: undefined,
      waterSystem: 'Fresh tank + city hookup',
      insulationRValue: 26,
      toiletType: 'Composting (OGO)',
      loftCount: 1,
      heatingType: 'Propane + electric',
      rainwaterCollection: true,
      greyWaterSystem: true,
    },
    amenities: ['Road Legal', 'Composting Toilet', 'Fresh Water Tank', 'Loft Bedroom', 'Dutch Door'],
    isFeatured: false,
    status: 'active',
    monthlyRent: 800,
    downPaymentPct: 20,
    financeTermMonths: 36,
    createdAt: '2024-03-20T10:00:00Z',
  },
];

export const getFeaturedListings = () => mockListings.filter((l) => l.isFeatured);
export const getListingsByType = (type: 'sale' | 'rent') =>
  mockListings.filter((l) => l.priceType === type || l.priceType === 'both');
export const getListingById = (id: string) => mockListings.find((l) => l.id === id);
